### ISSUE TITLE
Fix icons svg files

### ISSUE THREAD

**Issue by Winchestery** [ita-social-projects/what-front#120]
Fix icons svg files 
`<svg fill=""> <path fill=""></path> </svg>`
Delete "fill" attributes
In case of abiliti of adding colors to the Icon, 
and in `path fill = "none"`, this  means only a presence of a background , so chances are you don't have to delete it

**Comment by MarinaPasternak** [comment]
![photo_2020-11-20_01-05-16](https://user-images.githubusercontent.com/31963187/99735616-961bd200-2acd-11eb-923c-6f765e2fe73b.jpg)
