### ISSUE TITLE
Header layout

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#21]
Create example with using HTML and CSS.
Instead of Marks we should have "Progress" and add support button.

![header](https://user-images.githubusercontent.com/72501713/97876312-b78a6900-1d2c-11eb-9e2d-751e9aee03a7.jpg)

**Comment by Winchestery** [comment]
Edited mokup
![image](https://user-images.githubusercontent.com/56606870/98009319-14a21f80-1dfe-11eb-8e2f-5fc2f902a08a.png)
