### ISSUE TITLE
Schedule layout

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#22]
Create example with using HTML and CSS.
![Schedule](https://user-images.githubusercontent.com/72501713/97876512-033d1280-1d2d-11eb-82bf-8614e806c2f5.jpg)

**Comment by MarinaPasternak** [comment]
![image](https://user-images.githubusercontent.com/31963187/99466162-963c9600-2944-11eb-82b0-22b8e99068cc.png)

**Comment by MarinaPasternak** [comment]
![image](https://user-images.githubusercontent.com/31963187/99466943-fa138e80-2945-11eb-85f7-458e99c64ddf.png)
