### ISSUE TITLE
Edit mockup of student`s progress

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#23]
![Grades](https://user-images.githubusercontent.com/72501713/97876813-66c74000-1d2d-11eb-98d2-656909b33da8.jpg)

**Comment by iklopov** [comment]
My mockup:
https://ninjamock.com/Designer/Workplace/137512134/Page1

**Comment by Anastasiia0999** [comment]
**Pls add screenshot here**

![image](https://user-images.githubusercontent.com/55295369/97981839-8ddc4b00-1ddb-11eb-9ded-2f0c82b80ad2.png)

**What about tasks? Do we have them?**

**Comment by iklopov** [comment]
![image](https://user-images.githubusercontent.com/22566554/98215287-4a571d80-1f50-11eb-97c0-ccec4d7fa77a.png)

**Comment by iklopov** [comment]
![image](https://user-images.githubusercontent.com/22566554/98636304-44d24c80-232f-11eb-812e-abe9a8fd0ee5.png)

**Comment by iklopov** [comment]
![image](https://user-images.githubusercontent.com/22566554/98733181-d0d48a80-23a8-11eb-98ef-2a43f3b2d040.png)
