### ISSUE TITLE
Support layout

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#24]
Create example with using HTML and CSS.
![supportForm](https://user-images.githubusercontent.com/72501713/97877539-67aca180-1d2e-11eb-83ff-80baa34c8b7a.jpg)

**Comment by Winchestery** [comment]
![image](https://user-images.githubusercontent.com/56606870/98168646-8f009b80-1ef3-11eb-9080-2cee6f43bc30.png)
[Figma](https://www.figma.com/file/M6fVZ0uekH53hAIczX36sM/Untitled?node-id=24%3A18)
