### ISSUE TITLE
Edit mockup List of Lessons

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#27]
We do not need select mentor
If we have no lessons, just show us some message.
Change name of button to "add a lesson"
![MentorListofLessonss](https://user-images.githubusercontent.com/72501713/97986759-39d96280-1deb-11eb-9612-a5b0eea967a1.jpg)

**Comment by Winchestery** [comment]
Edited mockups
![image](https://user-images.githubusercontent.com/56606870/98009478-40250a00-1dfe-11eb-9609-451dc39523d2.png)
![image](https://user-images.githubusercontent.com/56606870/98009505-461aeb00-1dfe-11eb-8d79-bc20ccfde646.png)
