### ISSUE TITLE
Edit mockup Add a Lesson

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#28]
Change "start a lesson" to "add a lesson"
Delete "invite mentors",
Add date time
Add button "fill class register"
![Mentror_create-lessons](https://user-images.githubusercontent.com/72501713/97987363-32668900-1dec-11eb-9a85-b7e26fd6aea4.jpg)

**Comment by Winchestery** [comment]
![image](https://user-images.githubusercontent.com/56606870/98095177-e3276380-1e92-11eb-9a3b-5f7c87befb22.png)

[https://www.figma.com/file/M6fVZ0uekH53hAIczX36sM/Untitled?node-id=0%3A1](url)
