### ISSUE TITLE
Create mockup of filling class register

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#29]
Columns of marks and visits of group

**Comment by Winchestery** [comment]
![image](https://user-images.githubusercontent.com/56606870/98017881-8d0dde00-1e08-11eb-8db8-9125682c2d7b.png)

[https://www.figma.com/file/M6fVZ0uekH53hAIczX36sM/Untitled?node-id=0%3A1](url)
