### ISSUE TITLE
Edit mockup of List of groups

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#30]
It should be like List of Lessons(cards)
Add name of courses,
Delete finish date,
These cards should be clickable for details.
Add button "add group".
![Mentor_listofgroups](https://user-images.githubusercontent.com/72501713/97989417-8fb00980-1def-11eb-8ec4-d758cb156a78.jpg)

**Comment by Anastasiia0999** [comment]
_**[Figma Link](https://www.figma.com/file/M6fVZ0uekH53hAIczX36sM/Untitled?node-id=0%3A1)**_

![image](https://user-images.githubusercontent.com/55295369/98103993-8467e700-1e9e-11eb-85a3-d68e0bb2f435.png)
