### ISSUE TITLE
Create edit group layout

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#32]
Create example with using HTML and CSS
![Mentor_edit-group](https://user-images.githubusercontent.com/72501713/97991369-6d6bbb00-1df2-11eb-8c41-1391882b7a42.jpg)

**Comment by Winchestery** [comment]
![image](https://user-images.githubusercontent.com/56606870/98168827-d25b0a00-1ef3-11eb-8768-26d6b44b0120.png)
[Figma](https://www.figma.com/file/M6fVZ0uekH53hAIczX36sM/Untitled?node-id=0%3A1)
