### ISSUE TITLE
Groups page: 'Add group' page is not opened after clicking 'Add group' button

### ISSUE THREAD

**Issue by Aron1994** [ita-social-projects/what-front#417]
**Environment:** Windows 7 x64 Google Chrome Version 87.0.4280.141.
**Reproducible:** always.
**Build found:** https://github.com/ita-social-projects/what-front/projects

**Description**
'Add group' page is not opened after clicking 'Add group' button.

**Preconditions**

1. Administrator user exists in the system.
2. At least one group exists in the system.
3. WHAT system is opened --> User is logged as administrator user --> 'Groups' page is opened.

**Steps to reproduce**
1. Click 'Add group' button.

**Actual result**
'Add group' page is not opened.

**Expected result**
'Add group' page is opened.

"User story #WHAT-92"
[Test case](https://jira.softserve.academy/browse/WHAT-111)"

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Critical"), Type ("Functional").

**Attachment:**

![Screenshot_1](https://user-images.githubusercontent.com/67287394/104810668-df9f4980-57fe-11eb-975f-cff89408f113.png)

![Screenshot_2](https://user-images.githubusercontent.com/67287394/104810671-e463fd80-57fe-11eb-9ff0-9263647179fc.png)

**Comment by MozdolevskyiMaksym** [comment]
This component already exists

**Comment by AllaYakymova** [comment]
#417 
The component "StartGroup" has already added.
![image](https://user-images.githubusercontent.com/62800248/120287134-a2c48280-c2c7-11eb-8edc-a4878fafb4e3.png)

'Add group' button is working
