### ISSUE TITLE
Config scss file

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#42]
Create config scss file with fonts and colors(variables)

**Comment by Winchestery** [comment]
`_variables.scss`  file added:
**variables**
**maps**
**mixins**
_custom styles setted_

`index.html`  changed:
custom fonts added with using link:
*Libre Franklin
*Libre Baskerville 

`index.scss`  changed:
`@import 'src/style/_variables/scss`
