### ISSUE TITLE
Mockup lesson details

### ISSUE THREAD

**Issue by MozdolevskyiMaksym** [ita-social-projects/what-front#43]
Create mockup Lesson details
It can be like:
![image](https://user-images.githubusercontent.com/72501713/98119372-9442f380-1ebd-11eb-85f1-eacfb2878e12.png)

**Comment by Winchestery** [comment]
![image](https://user-images.githubusercontent.com/56606870/98167552-eaca2500-1ef1-11eb-8952-f3b223987e5f.png)

[](https://www.figma.com/file/M6fVZ0uekH53hAIczX36sM/Untitled?node-id=0%3A1)
