### ISSUE TITLE
Student details page: 404 error is not shown after changing ID on invalid in browser URL.

### ISSUE THREAD

**Issue by vitalii-skrynnyk** [ita-social-projects/what-front#436]
**Environment:** Windows 10 x 64 V. 1909; Firefox Browser 84.0.1.
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/what-front/tree/dev

**Description**
404 error is not shown after changing ID on invalid in browser URL.

**Preconditions**
1.  Administrator user exists in system.
2. At least one student exists in system.
3. WHAT system is opened --> User is logged as administrator user --> 'Students' page is opened.

**Steps to reproduce**
1. Click any student's card.
2. Change student's ID on invalid data in the URL.
3. Press Enter button.

**Actual result**
There is 'Loader' is shown in the page.
![2](https://user-images.githubusercontent.com/66641975/104949587-df05df00-59c7-11eb-8173-d848b55de422.jpg)

**Expected result**
404 error is shown.

**Labels to be added**
"Bug", Priority ("pri: Low "), Severity ("severity: Minor"), Type ("Functional")

**Comment by ferbiy** [comment]
Already fixed
