### ISSUE TITLE
Edit secretary tab: Fire button does not delete secretary from the system

### ISSUE THREAD

**Issue by vladshkut** [ita-social-projects/what-front#437]
**Environment:** Windows 10 Pro.  Google Chrome  87.0.4280.141
**Reproducible:** always 
**Build found:**  https://github.com/ita-social-projects/what-front/projects

**Preconditions**
1.  Open What website > login as exists Admin > click Secretary header tab>Select any exists secretary from list of secretaries >click Edit icon
**Steps to reproduce**
1.Click Fire button
2.Click "Confirm" button(on popup window)

**Actual result**
 "This **secretsry** account is already disabled" message appears. Secretary is still in the system, **Fire** button is disabled for all secretaries 

**Expected result**
The deleted secretary does not display in the list of secretaries.

**User story and test case links**
https://jira.softserve.academy/browse/WHAT-65
https://github.com/ita-social-projects/what-front/wiki/SRS-Edit-Secretary

**Labels to be added**
"Bug", Priority ("Low"), Severity ("medium"), Type ("Functional"),

**Comment by Icemandov** [comment]
- already fixed

**Comment by AllaYakymova** [comment]
Laying off the secretaries is working.
Worker with id=4 is deleted 
![image](https://user-images.githubusercontent.com/62800248/120295727-166a8d80-c2d0-11eb-9616-9ea8ed8d7c1b.png)
His activity in db changed on "0" (disable):
![image](https://user-images.githubusercontent.com/62800248/120296235-985ab680-c2d0-11eb-91c6-f64cb6784bb8.png)
and his name is already in the disabled list after reloading of the page:
![image](https://user-images.githubusercontent.com/62800248/120296455-cdff9f80-c2d0-11eb-8e7f-b7219b7940e4.png)
