### ISSUE TITLE
Add a Lesson: Impossible to create a new lesson

### ISSUE THREAD

**Issue by Anzhelika-m** [ita-social-projects/what-front#440]
**Environment:** Windows 10x64 Google Chrome Version 87.0.4280.141
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/what-front/projects

**Description** 
A new lesson is not added after filling all required fields with valid data and clicking the "Save" button on the 'Add a Lesson' page

**Preconditions**

1. WHAT project is opened.
2. The Administrator is registered in the system.
3. The Administrator is logged in.
4. 'Lessons' page is opened.

**Steps to reproduce**
1. Click the 'Add a Lesson' button.
2. Enter "Test Lesson" data in the 'Lesson Theme' text field.
3. Select 'Group1' data from the 'Group Name' combo-box list.
4. Select [today-1 01:00 PM] data from the 'Lesson Date/Time' date picker.
5. Click the 'Class Register' button.
6. Check 'Presence' checkbox for 'Student1'.
7. Click 'Save' button

**Actual result**
Impossible to save a new lesson. The new lesson was not added, the user remained on the "Add lesson" page.

**Expected result**
A new lesson is added after filling all required fields with valid data and clicking the "Save" button on the 'Add a Lesson' page

[Test case](https://jira.softserve.academy/browse/WHAT-87)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:Critical"), Type ( "Functional")

**Comment by MozdolevskyiMaksym** [comment]
This bug is fixed from our side, but we still cannot create a new lesson, because of response from server.

**Comment by anton-sedchenko** [comment]
The bug is not reproduced. New groups are added.
