### ISSUE TITLE
SignInPage_LogInto_system_Invalid 'Password' field

### ISSUE THREAD

**Issue by voievoda** [ita-social-projects/what-front#450]
Environment: Windows 10 Pro. Google Chrome 87.0.4280.141
Reproducible: always
Build found: https://github.com/ita-social-projects/what-front/projects

Preconditions
1. WHAT app is opened
2. The user is registered in the system 
3. The user isn't logged in 
4. The 'Sign in' page is opened

Steps to reproduce
1. Fill 'Email address' field with valid test data 
2. Fill 'Password' field with invalid test data 
3. Click 'Sign in' button 

Actual result
Error page appears
Expected result
'Invalid credentials' red error message appears under the 'Sign in' button
Postconditions

User story and test case links
https://jira.softserve.academy/browse/WHAT-51
https://jira.softserve.academy/browse/WHAT-63

Labels to be added
"Bug", Priority ("Low"), Severity ("medium"), Type ("functional"),

**Comment by CaelumVallis** [comment]
The bug can't be reproduced
![image](https://user-images.githubusercontent.com/64030284/120444023-e5ea2880-c38f-11eb-9e37-bc05a6ef5673.png)
