### ISSUE TITLE
RegistrationPage_UserRegistration_ValidData

### ISSUE THREAD

**Issue by voievoda** [ita-social-projects/what-front#452]
Environment: Windows 10 Pro. Google Chrome 87.0.4280.141
Reproducible: always
Build found: https://github.com/ita-social-projects/what-front/projects

Preconditions
1. WHAT app is opened 
2. The 'Sign in' page is opened 
3. The 'Registration' page is opened

Steps to reproduce
1. Fill 'First Name' field with test data  'Lana'
2. Fill 'Last Name' field with  test data 'Rey'
3. Fill 'Email address' with test data 'lanam@gmail.com'
4. Fill the 'Fill 'Password' field with test data' field with test data 'lanarey2021'

Actual result
'Password' field  'Must contain at least one uppercase, one lowercase, one number'
Expected result
Test data is displayed as asterisks in the 'Confirm Password' field

Postconditions

User story and test case links
https://jira.softserve.academy/browse/WHAT-52
https://jira.softserve.academy/browse/WHAT-73

Labels to be added
"Bug", Priority ("Hight"), Severity ("critical"), Type ("functional"),

**Comment by CaelumVallis** [comment]
fixed by #611
