### ISSUE TITLE
Layout moving with open sidebar

### ISSUE THREAD

**Issue by VladyslavPolushyn** [ita-social-projects/what-front#528]
- Make layout moving with the sidebar opening (from 769px to 1919px)

![Безымянный](https://user-images.githubusercontent.com/32390003/106757098-a35e4c80-6638-11eb-9491-dd1689626ec2.jpg)

**Comment by R0D1N** [comment]
also, making sidebar "onClick" feature

**Comment by so2niko** [comment]
769px is too small for it. 
Let it work from 992px
