### ISSUE TITLE
Update student groups model

### ISSUE THREAD

**Issue by VladyslavPolushyn** [ita-social-projects/what-front#536]
- add new endpoint to the model `GET ​/api​/student_groups​/{id}​/homeworks `

**Comment by ViktoriiaKR** [comment]
Added a request to the model GET ​/api​/student_groups​/{id}​/homeworks. An empty array is received in response to the request
![res](https://user-images.githubusercontent.com/58779629/121204648-b2236d00-c87f-11eb-89f5-45aca64a8ee9.PNG)
![res_group_homeworks](https://user-images.githubusercontent.com/58779629/121204684-b8194e00-c87f-11eb-8689-1d2e2ebe374d.PNG)
![empty](https://user-images.githubusercontent.com/58779629/121204713-bfd8f280-c87f-11eb-84e4-9536cec546d1.PNG)
