### ISSUE TITLE
Homework mockup

### ISSUE THREAD

**Issue by VladyslavPolushyn** [ita-social-projects/what-front#538]
Create homework mockup:
- add homework mockup
- edit homework mockup

**Comment by MarinaPasternak** [comment]
![image](https://user-images.githubusercontent.com/31963187/108356470-3aaccd80-71fd-11eb-9b7b-1c415b8315c9.png)
![image](https://user-images.githubusercontent.com/31963187/108356574-5c0db980-71fd-11eb-89e3-061f25fa5f2c.png)
![image](https://user-images.githubusercontent.com/31963187/108356594-616b0400-71fd-11eb-83a7-74e27ccfa74d.png)
