### ISSUE TITLE
fix: add group

### ISSUE THREAD

**Issue by MarinaPasternak** [ita-social-projects/what-front#568]
you can add group only without mentors and students

**Comment by CaelumVallis** [comment]
@MarinaPasternak , "you can add group only without mentors and students" is it expected or current behaviour?

**Comment by CaelumVallis** [comment]
The bug doesn't represent.
You can add group either with mentors and students or without them.

https://user-images.githubusercontent.com/64030284/121249339-26283a00-c8ad-11eb-9da2-af51abe8899e.mp4


https://user-images.githubusercontent.com/64030284/121249348-29232a80-c8ad-11eb-8b10-4ce0e7a524bc.mp4

**Comment by so2niko** [comment]
ok
