### ISSUE TITLE
AuthorizationPage_'Forgot Password'_link_is_ not_open_'Forgot password'_form

### ISSUE THREAD

**Issue by NORDBBFG** [ita-social-projects/what-front#572]
**Environment:** Windows 10, Yandex browser (20.8.0.903) version.
**Reproducible:** always.
**Build found:** 73b9101 commit from https://github.com/ita-social-projects/what-front

**Preconditions**
Open WHAT 'Authorization' page

**Steps to reproduce**
1. Click 'Forgot Password' link

**Actual result**
'Authorization' page is opened

**Expected result**
‘Forgot Password’ form is opened 

**User story and test case links**
[Test case](https://jira.softserve.academy/browse/WHAT-188)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:minor "), Type ("Functional").

**Comment by so2niko** [comment]
**Build found: last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev** ??
Why GreenCityClient ?

**Comment by 7SergSmith7** [comment]
Now Actual result:
‘Forgot Password’ form is opened
![image](https://user-images.githubusercontent.com/30880200/120527292-d811c300-c3e2-11eb-8895-e15b74fe2f72.png)

**Comment by so2niko** [comment]
Nice.
It seems, this was old version of build.
