### ISSUE TITLE
StudentDetails_ListOfLessons_NotDisplayed

### ISSUE THREAD

**Issue by MashaLar** [ita-social-projects/what-front#573]
**Environment:** Windows 8.1, GoogleChrome, v89.0.4389.114
**Reproducible:** always
**Build found:** commit 73b9101 from https://github.com/ita-social-projects/what-front 

**Preconditions**
WHAT project opened.
$Student1 (student role) is registered in system and $User1 (any other type of role) is registered in system.
Log in with registered $User1.

**Steps to reproduce**
1. Open ‘List of Students’ page.
2. Open $Student1`s ‘Student details’ page.

**Actual result**
‘Loader’ component is displayed for eternity. (StudentDetailsLessonError,  StudentDetailsLessonLoading)

**Expected result**
‘Loader’ component disappeared in ‘Lessons’ component. List of current lessons for $Student1 is displayed.

**Postconditions**
Log out $User1.

**Test case link**
[Test case](https://jira.softserve.academy/browse/WHAT-197)

**Labels to be added**
Bug, _pri:_ high, _severity:_ critical, Functional.

![StudentDetailsLessonLoading](https://user-images.githubusercontent.com/69858048/114313170-1fc05080-9afe-11eb-9624-37d4916ab935.png)

![StudentDetailsLessonError](https://user-images.githubusercontent.com/69858048/114313169-1e8f2380-9afe-11eb-8bce-d3b4f0521058.png)

**Comment by 7SergSmith7** [comment]
If I understood correctly, the problem went away after moving to a new backend.

**Comment by 7SergSmith7** [comment]
https://user-images.githubusercontent.com/30880200/121086861-5eb40f00-c7ec-11eb-81c7-3cd3187fa9e6.mp4
