### ISSUE TITLE
StudentEdit_SaveButton_DisabledAfterChanges

### ISSUE THREAD

**Issue by MashaLar** [ita-social-projects/what-front#574]
**Environment:** Windows 8.1, GoogleChrome,  v89.0.4389.114
**Reproducible:** always
**Build found:** commit 73b9101 from https://github.com/ita-social-projects/what-front 

**Preconditions**
WHAT project opened.
$Student1 (student role) is registered in system and $User1 (any other type of role like Admin, Secretary or Mentor) is registered in system.
Log in with registered $User1.

**Steps to reproduce**
1. Open $Student1 ‘Student details’ page. 
2. Click ‘Edit Student’ tab. (StudentEditInitialState)
3. Click ‘Group`s’ drop-down list.
4. Choose one of group that $Student1 doesn`t have.
5. Click ‘plus’ button.

**Actual result**
‘Save’ button is disabled and not clickable. (StudentEditAddedChanges)

**Expected result**
‘Save’ button is enabled. ‘Save’ button is clickable and saves all changes. After ‘Save’ button is clicked message about successful saved changes is displayed.

**Postconditions**
Log out $User1.

**Test case link**
[Test case](https://jira.softserve.academy/browse/WHAT-102)

**Labels to be added**
Bug, _pri:_ high, _severity:_ critical, Functional.

StudentEditInitialState
![StudentEditInitialState](https://user-images.githubusercontent.com/69858048/114313840-e63d1480-9b00-11eb-865f-bab09ab6e567.png)
StudentEditAddedChanges
![StudentEditAddedChanges](https://user-images.githubusercontent.com/69858048/114313843-e6d5ab00-9b00-11eb-92cb-f3b50ce2431f.png)

**Comment by D-mezentseff** [comment]
Баг утилизирован, без изменения кода, пара тестов: 

https://user-images.githubusercontent.com/82518924/121041844-cb62e580-c7bb-11eb-9e45-1cdc95ef069d.mp4

https://user-images.githubusercontent.com/82518924/121042220-2268ba80-c7bc-11eb-93bb-5bd4eb1c408d.mp4
