### ISSUE TITLE
"Groups table data doesn’t correspond to ‘Group tabs’ component data"

### ISSUE THREAD

**Issue by ianagez** [ita-social-projects/what-front#578]
**Environment:**  Windows 10, GoogleChrome  89.0.4389.114
**Reproducible:** always
**Build found:** commit 73b9101 from https://github.com/ita-social-projects/what-front

**Preconditions**
1.	WHAT project is opened.
2.	Log in as Admin | Secretary | Mentor.
3.	At least one excluded student exists.
4.	At least one groups exists.
5.	Add group for excluded student in ‘Student card'.

**Steps to reproduce**
 1.Go to 'Groups' page.
 2.Click 'Groups' table row which contains group with excluded student.

**Actual result**
Quantity of students is different in ‘Groups’ table and in ‘Group details’, ‘Edit group’ tabs.

**Expected result**
Group data from ‘Groups’ table corresponds to data in ‘Group details’, ‘Edit group’ tabs.

**Postconditions**
Delete group from excluded student ‘Student card'.

**User story and test case links**
E.g.: "User story WHAT-92,  WHAT-93,  WHAT-94
[Test case]( https://jira.softserve.academy/browse/WHAT-217#)"

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor "), Type ( "Functional").

**Attachment**
![Знімок екрана (319)](https://user-images.githubusercontent.com/24384239/114506527-99f5ef80-9c3a-11eb-8039-e104622aadd0.png)
![Знімок екрана (320)](https://user-images.githubusercontent.com/24384239/114506528-9b271c80-9c3a-11eb-8287-0e3fa7a6da00.png)

**Comment by ViktoriiaKR** [comment]
#578 
In the data with a list of students of a specific group comes an array, which contains the ID of non-existent students (in the database with the label "0").
![group](https://user-images.githubusercontent.com/58779629/120375048-f9ab7580-c322-11eb-9d26-d8da223441ca.PNG)
![info](https://user-images.githubusercontent.com/58779629/120375063-016b1a00-c323-11eb-8044-23687705dc84.PNG)
![data](https://user-images.githubusercontent.com/58779629/120375075-06c86480-c323-11eb-9691-6936625d2646.PNG)

**Comment by RomanVishnevetskyi** [comment]
Bug was fixed with update  on backend side.

<img width="1132" alt="Снимок экрана 2021-09-18 в 13 35 32" src="https://user-images.githubusercontent.com/58218838/133887264-cd77d129-840c-480e-b55b-83fc14b00b01.png">
<img width="676" alt="Снимок экрана 2021-09-18 в 13 35 42" src="https://user-images.githubusercontent.com/58218838/133887268-b3a172c1-d54c-4881-a977-645570a7b2f8.png">
