### ISSUE TITLE
RegistrationPage_ImpossibleUserRegistration_ValidData

### ISSUE THREAD

**Issue by BolsunovaNataliia** [ita-social-projects/what-front#579]
**Environment:** Windows 10 Pro. Google Chrome 87.0.4280.141.
**Reproducible:** always
**Build found:** 739101 commit from https: github/ita/social-projects/what-front

**Preconditions**
1.	WHAT app is opened
2.	The 'Registration' page is opened

**Steps to reproduce**
1.	Fill 'First Name' field with valid data
2.	Fill 'Last Name' field with valid data
3.	Fill 'Email address' field with valid data 
4.	Fill 'Password' field with valid data (Password must contain at least one uppercase, one lowercase, Latin, one number character)
5. Move cursor to 'Confirm Password' field.
6. Pay attention to the appearance of a message "Must contain at least one uppercase, one lowercase, one number" highlighted in red below the Password field.

**Actual result**
A warning message in red is displayed below the ‘Password’ field: "Must contain at least one uppercase, one lowercase, one number"
Attached bug screenshots.

**Expected result**
Password is displayed as asterisks in the ‘Password' field

**User story and test case links**
https://jira.softserve.academy/browse/WHAT-52
https://jira.softserve.academy/browse/WHAT-73

**Labels to be added**
"Bug", Priority ("High"), Severity ("critical"), Type ("Functional")
![bug_registration](https://user-images.githubusercontent.com/79742732/114551075-9333a080-9c6b-11eb-989c-d201e3593939.jpg)
.

**Comment by CaelumVallis** [comment]
duplicates #452 and #455
fixed by #611
