### ISSUE TITLE
['Edit a Lesson' page] The error message isn't displayed after entering 101 characters in the 'Lesson Theme' field

### ISSUE THREAD

**Issue by Ann-5** [ita-social-projects/what-front#582]
**Environment:** Windows 7x64, Google Chrome 90.0.4430.93 
**Reproducible:** always
**Build found:** 318d8f1  commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

**Preconditions**
1. WHAT project opened.
2. Mentor or Admin user is existed in the system
3. At least 1 lesson is existed in  lesson grid. 
4. The 'List of Lessons' page is opened after clicking the 'Lessons' tab
5. 'Edit a lesson' page is opened after clicking Edit icon in the first row of the table 

**Steps to reproduce**
1. Enter 101 characters in 'Lesson Theme' field
2. Enter 201 characters in 'Lesson Theme' field 

**Actual result**
The error message 'too long' is appeared under 'Lesson Theme' field after entering 201 characters in the field. 

**Expected result**
The error message 'too long' is appeared under 'Lesson Theme' field after entering 101 characters in the field. 

![Screenshot_15](https://user-images.githubusercontent.com/84627655/120084191-fa4fcc00-c0d6-11eb-8d9d-030ea02d99d1.png)
![Screenshot_16](https://user-images.githubusercontent.com/84627655/120084192-fb80f900-c0d6-11eb-80b2-5f8e3b4677fd.png)
![Screenshot_17](https://user-images.githubusercontent.com/84627655/120084193-fb80f900-c0d6-11eb-9ab0-c16fe98c844f.png)

**Labels to be added**
"Bug", Priority ("medium"), Severity ("major"), Type ("Functional")

**Comment by so2niko** [comment]
**100 symbols**

info at #603
