### ISSUE TITLE
['Sign up to WHAT' page] The pop-up 'Congratulations' window isn't opened when user tries to register

### ISSUE THREAD

**Issue by Sanvole** [ita-social-projects/what-front#590]
Environment: Windows 10 (x64) - Edge v. 90
Reproducible: always.
Build found: 318d8f1 commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

**Preconditions**

1. WHAT project launched locally using npm.
2. The project is opened in the browser. URL: 'localhost:8080/auth'.

**Steps to reproduce**

1. Click 'Registration' link.
2. Fill the registration form with valid data.
3. Click 'Sign up' button.

**Actual result**
Error message 'Cannot create account' is appeared under 'Sign up' button.

**Expected result**
The pop-up 'Congratulations' window is opened with the text 'You have successfully registered. Please, wait until your account is approved and role is assigned.'. 'Ok' button is enabled.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").
![Screenshot_43 (1)](https://user-images.githubusercontent.com/82441384/120200975-97bd1400-c22d-11eb-90c1-ac7ae9560562.jpg)

**Comment by CaelumVallis** [comment]
Seems to be a back-end problem, error appears in any case (with valid data too), pic related

![image](https://user-images.githubusercontent.com/64030284/121022779-55ef1900-c7ab-11eb-835a-1cc211c24f83.png)

**Comment by AnatoliiAA** [comment]
Can't reproduce the bug on the current version of the backend. After successful registration, a popup appears.
![image](https://user-images.githubusercontent.com/44525659/135323903-a87f538e-4445-427f-802c-7c8770da097c.png)
