### ISSUE TITLE
['Sign up to WHAT' page] The user can enter the password with whitespace sign

### ISSUE THREAD

**Issue by Sanvole** [ita-social-projects/what-front#592]
Environment: Windows 10 (x64) - Edge v. 90
Reproducible: always.
Build found: 318d8f1 commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

**Preconditions**

1. WHAT project launched locally using npm.
2. The project is opened in the browser. URL: 'localhost:8080/auth'.

**Steps to reproduce**

1. Click 'Registration' link.
2. Enter password into 'Password' field with whitespace and special sign.
3. Onblur the field.

**Actual result**
There is no any messages, the whitespace is allowed to enter in the field.

**Expected result**
The red message 'Password must contain at least one uppercase, one lowercase, Latin, one number character' is displayed under the field.

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("low"), Type ("UI").

**Comment by 7SergSmith7** [comment]
There is no requirements that the Password field shouldn't contain whitespaces.
This isn't a bug.
