### ISSUE TITLE
[Mentor details tab/Student details tab] The 'Arrow' button, which redirects the user to the previous component is absent 

### ISSUE THREAD

**Issue by tanyamun** [ita-social-projects/what-front#595]
**Environment:** Windows 10 (x64) - Chrome v. 90
**Reproducible:** always
**Build found:** 318d8f1 commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

**Description:** [Mentor details tab] The 'Arrow' button, which redirects the user with Admin, Secretary  role to the 'Mentors' table is absent. 
[Student details tab] The 'Arrow' button, which redirects the user with Admin, Secretary and Mentor role to the 'Students' table is absent.

**Preconditions**

1. WHAT project is opened . 
2. The users with Admin, Secretary, Mentor and Student roles are created in the system.(active)
3. [Student details tab]- The user with  role ( roles: Admin/Secretary/Mentor)  is logged in the system. / [Mentor details tab] - The user with  role ( roles: Admin/Secretary )  is logged in the system.
4.  [Student details tab]- The user with role ( roles: Admin, Secretary Mentor)  is on the 'Students' page and the 'Students' table is shown. At least 1 user with Student role is displayed in the 'Students' table. / [Mentor details tab] - The user with role ( roles: Admin/Secretary)  is on the 'Mentors' page and the 'Mentors' table is shown. At least 1 user with Mentor role is displayed in the 'Mentors' table.

**Steps to reproduce**

 [Student details tab]
1. Click on the 'Students' table row which contains the information about the user with the role of Student.
2. Verify that 'Arrow' button is present and located to the left of the 'Student details' tab.

[Mentor details tab] 
1. Click on the 'Mentors' table row which contains the information about the user with the role of Mentor.
2. Verify that 'Arrow' button is present and located to the left of the 'Mentor details' tab.

**Actual result**
   [Student details tab]  The 'Arrow' button, which redirects the user with Admin , Secretary or Mentor   role to the 'Students' table is absent. 
  [Mentor details tab] The 'Arrow' button, which redirects the user with Admin , Secretary    role to the 'Mentors' table is absent. 

**Expected result**
 [Student details tab]    The  'Arrow' button, which redirects the user with Admin , Secretary or Mentor  role to the 'Students' table is present and located to the left of the 'Student details' tab.
 [Mentor details tab]The  'Arrow' button, which redirects the user with Admin , Secretary   role to the 'Mentors' table is present and located to the left of the 'Mentor details' tab.

![Actual result - mentor details](https://user-images.githubusercontent.com/84660530/120238709-6a8c5800-c265-11eb-97da-f08668c735b8.png)
![Actual Result student details](https://user-images.githubusercontent.com/84660530/120238716-6ceeb200-c265-11eb-8296-32a935c3a723.png)

![Arrow button - mentor details](https://user-images.githubusercontent.com/84660530/120238673-5a747880-c265-11eb-82ef-d49c720cd048.png)
![Arrow button - student details](https://user-images.githubusercontent.com/84660530/120238681-5ea09600-c265-11eb-9c19-93ce1dd875b6.png)

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by CaelumVallis** [comment]
bug doesn't represent
![image](https://user-images.githubusercontent.com/64030284/121952532-0b4e3d80-cd65-11eb-9d79-e0ad78d5e112.png)
![image](https://user-images.githubusercontent.com/64030284/121952547-130de200-cd65-11eb-99a3-0fbdc1c560fd.png)
