### ISSUE TITLE
['Edit a Lesson' page] The 'Mark' field is displayed '0' value in the Class Register table

### ISSUE THREAD

**Issue by Ann-5** [ita-social-projects/what-front#599]
**Environment:** Windows 7x64, Google Chrome 90.0.4430.93
**Reproducible:** always
**Build found:** 318d8f1 commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

**Preconditions**
WHAT project is opened 
Mentor user is existed in the system
At least 1 lesson is added to the lesson table. 
Mentor user is logged in the system
'Lessons' page is opened after clicking 'Lessons' tab
'Edit a lesson' page is opened after clicking Edit icon in the first row of the table 
 

**Steps to reproduce**
1. Uncheck any checkbox in the 'Presence' field of the Class Register table
2. Pay attention to '0' value in inactive 'Mark' field
3. Check the same checkbox in the 'Presence' field
4. Pay attention to '0' value in the active 'Mark' field

**Actual result**
The 'Mark' field is displayed '0' value after checking/unchecking the 'Presence' checkbox 

**Expected result**
The active 'Mark' field is displayed '1' value after checking the 'Presence' checkbox 
The disable 'Mark' field is empty after unchecking the 'Presence' checkbox 

**Labels to be added**
"Bug", Priority ("low"), Severity ("minor"), Type ("UI")

![Mark field 1](https://user-images.githubusercontent.com/84627655/120272522-e9a97c80-c2b5-11eb-8296-173faf61301b.png)
![Mark field](https://user-images.githubusercontent.com/84627655/120272525-eadaa980-c2b5-11eb-973d-5523b6c72875.png)

**Comment by AllaYakymova** [comment]
According to srs marks are unavailable when presence is false. The mark field is empty when presence is false.
When the presence is true, the mark field may be empty or contain the mark.

https://github.com/ita-social-projects/what-front/wiki/SRS-Edit-a-Lesson

Assumption about:
 ```Expected result
The active 'Mark' field is displayed '1' value after checking the 'Presence' checkbox ```
is not a necessary condition
