### ISSUE TITLE
['Schedule tab'] When user with role 'Student' try to click on 'Schedule' tab error page appears.

### ISSUE THREAD

**Issue by Nikk2world** [ita-social-projects/what-front#600]
Environment: Windows 10 x64,  Opera v.75.0.3969.
Reproducible: always.
Build found: 318d8f1 ;  last commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

Preconditions
1.'What' project is open by  local host (http://localhost:8080/my-profile).
2. User with 'Student' role is exist and logged into system.

Steps to reproduce
1. Select from the list of tabs 'Schedule' that located in the left side of page.
2. Appears new page with 404 error 'This page is missing'.

Actual result
1. Page with 404  error 'This page is missing'  is open.

Expected result
1. Appears page 'Schedules' with information about events.

Software Requirements Stories
https://github.com/ita-social-projects/what-front/wiki/SRS

Labels to be added
"Bug", Priority 'High' ; Type "Functional".
![Screenshot_112](https://user-images.githubusercontent.com/84771802/120278920-87a14500-c2be-11eb-9b84-218a0748e7da.jpg)

**Comment by CaelumVallis** [comment]
bug doesn't represent
![image](https://user-images.githubusercontent.com/64030284/122009463-c8bb4e00-cdc2-11eb-8cc7-2ca5edd3edf5.png)
