### ISSUE TITLE
['Lesson Details' page] Two fields 'Lesson Date' and 'Lesson Time' are displayed on the page

### ISSUE THREAD

**Issue by Ann-5** [ita-social-projects/what-front#602]
**Environment:** Windows 7x64, Google Chrome 90.0.4430.93
**Reproducible:** always
**Build found:** 318d8f1 commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

**Preconditions**
1. WHAT project is opened 
2. Secretary is existed in the system
3. At least 1 lesson is added to the lesson table
4. Secretary user is logged in the system
5. The 'Lessons' page is opened after clicking the 'Lessons' tab

**Steps to reproduce**
1. Click the lesson row of the first lesson in the table
2. Pay attention to 'Lesson Date' and 'Lesson Time' fields

**Actual result**
The 'Lesson Date' and 'Lesson Time' fields are displayed on the 'Lesson Details' page

**Expected result**
The 'Lesson Date/Time' field is displayed on the 'Lesson details' page

**Labels to be added**
"Bug", Priority ("low"), Severity ("minor"), Type ("UI")

![Lesson details](https://user-images.githubusercontent.com/84627655/120289485-02bc2880-c2ca-11eb-9ef0-e2aa96d0783f.png)
![Screenshot_28](https://user-images.githubusercontent.com/84627655/120289881-6cd4cd80-c2ca-11eb-81af-021a6e0d0c3c.png)
![Screenshot_29](https://user-images.githubusercontent.com/84627655/120289883-6d6d6400-c2ca-11eb-8631-e0d787921682.png)

**Comment by 7SergSmith7** [comment]
There wasn't UI decision to separate these fields
