### ISSUE TITLE
['Add a Lesson' page] The error message isn't displayed after entering 101 characters in the 'Lesson Theme' field

### ISSUE THREAD

**Issue by Keyxnx** [ita-social-projects/what-front#603]
Environment: Windows 7x64, Google Chrome 90.0.4430.93
Reproducible: always
Build found: 318d8f1 commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

Preconditions

WHAT project opened.
Mentor or Admin user is existed in the system
Add lesson

Steps to reproduce

Enter 101 characters in 'Lesson Theme' field
Enter 201 characters in 'Lesson Theme' field
Actual result
The error message 'too long' is appeared under 'Lesson Theme' field after entering 201 characters in the field.

Expected result
The error message 'too long' is appeared under 'Lesson Theme' field after entering 101 characters in the field.

**Comment by so2niko** [comment]
Length of '_Lesson Theme_' field is **100** symbols
