### ISSUE TITLE
[Sign In Page] Error "Incorrect credentials" on Sign In page, when we use spaces before/after email

### ISSUE THREAD

**Issue by ferbiy** [ita-social-projects/what-front#607]
**Environment:** Windows 10 Pro, Firefox, 88.0.1 (64-bit).
**Reproducible:** always.
**Build found:** https://github.com/ita-social-projects/what-front/tree/dev

**Preconditions**
1. WHAT app is opened
2. The user is registered in the system 
3. The user isn't logged in 
4. The 'Sign in' page is opened

**Steps to reproduce**
1. Fill 'Email address' field with valid test data.
2. Add spaces before/after 'Email address' data.
3. Fill 'Password' field with valid test data.
4. Click 'Sign in' button.

**Actual result**
'Invalid credentials' red error message appears under the 'Sign in' button.

**Expected result**
Correct sign in even with spaces before/after email address.

**Additionally**
This case is not covered in the Software Requirements Specification. It is necessary to clarify the SRS to close the issue or fix it using trim() for email field. 

**User story and test case links**
![image](https://user-images.githubusercontent.com/42357921/120297310-a65d0700-c2d1-11eb-89d5-85c2703d7f36.png)
![image](https://user-images.githubusercontent.com/42357921/120298828-1455fe00-c2d3-11eb-9e18-883c3a61316d.png)

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Low"), Type ("Functional").

**Comment by 7SergSmith7** [comment]
![image](https://user-images.githubusercontent.com/30880200/120530266-ff1dc400-c3e5-11eb-84f8-d806b3b585a9.png)
![image](https://user-images.githubusercontent.com/30880200/120530344-13fa5780-c3e6-11eb-87e7-860cc1429e5e.png)

**Comment by 7SergSmith7** [comment]
When sending a request, unnecessary spaces are deleted.

**Comment by 7SergSmith7** [comment]
https://user-images.githubusercontent.com/30880200/120543343-e4068080-c3f4-11eb-8ed0-7411bca6c992.mp4

**Comment by ferbiy** [comment]
![image](https://user-images.githubusercontent.com/42357921/120644517-19a47b80-c480-11eb-84d8-df499070f179.png)
It is working correct in Chrome, but check the bug in Firefox.
