### ISSUE TITLE
[Course Details Page] The button arrow is missed to the left of the 'Course details' tab

### ISSUE THREAD

**Issue by InnaMusikhina** [ita-social-projects/what-front#613]
Environment: Windows 7x64, Google Chrome 90.0.4430.93
Reproducible: always
Build found: 318d8f1 commit from https://github.com/ita-social-projects/what-front/tree/taqc-bug-fix

Pre-conditions:

WHAT project is opened by local host http://localhost:8080/
One of the users (Admin/Secretary) is existed in the system
At least 1 course is added to the lesson table. 
The (Admin/Secretary) user is logged in the system
The 'Courses' page is opened after clicking the 'Courses' tab
The Courses table is displayed at least 1 course
Click the course row of the first course in the table. The user is redirected to the 'Course Details' tab. 

Steps to Reproduce:
Click the Button arrow, to the left of the 'Course details' tab.

Expected result:
The user is redirected to the Course List. 

Actual result:
The button arrow is missed to the left of the 'Course details' tab.

Labels to be added
![Screenshot 2021-06-02 at 11 53 59](https://user-images.githubusercontent.com/84676736/120452012-96f5c080-c39a-11eb-95d4-7d847e494691.png)
![Screenshot 2021-06-02 at 11 54 55](https://user-images.githubusercontent.com/84676736/120452157-aecd4480-c39a-11eb-8511-b4b404ca7434.png)

"Bug", Priority (" High"), Severity ("minor"), Type ("functional")

**Comment by CaelumVallis** [comment]
bug doesn't represent
![image](https://user-images.githubusercontent.com/64030284/121952354-c924fc00-cd64-11eb-896e-e279a9da66ce.png)
