### ISSUE TITLE
Add or Edit page on SRS for passwords

### ISSUE THREAD

**Issue by so2niko** [ita-social-projects/what-front#615]
password must be:
min length: 8
max length: 16
1 lower case
1 upper case
1 number
1 special char (!@#$%^&*()_+-=)

**Comment by anogire** [comment]
Edited pages:
Registration https://github.com/ita-social-projects/what-front/wiki/SRS-Registration
Change Password https://github.com/ita-social-projects/what-front/wiki/SRS-Change-Password
Reset Password https://github.com/ita-social-projects/what-front/wiki/SRS-Reset-Password
