### ISSUE TITLE
No excess to mentor and group info when user is a student

### ISSUE THREAD

**Issue by AllaYakymova** [ita-social-projects/what-front#646]
#Problem:
### The mentor name and group name are not available when customer role is 1 (student). 
status code 403 Forbidden
![image](https://user-images.githubusercontent.com/62800248/122013592-00c49000-cdc7-11eb-8429-1eb27c0e4599.png)

(get request ```/api/student_groups/{id}``` is only for roles = 2,3,4)
(get requests ```/api/mentors/{id}``` and ```/api/mentors/``` is only for roles = 2,3,4 and ```/api/mentors/{id}```  is not even presents in wiki (but it is in Swagger)
![image](https://user-images.githubusercontent.com/62800248/121667983-7ffa5100-cab3-11eb-8ff1-e7e01117775b.png)

**Comment by AllaYakymova** [comment]
# Unresolved problems:
## 1. The mentor name and group name are not available for display on the page 
(get request ```/api/student_groups/{id}``` is only for roles = 2,3,4)
(get requests ```/api/mentors/{id}``` and ```/api/mentors/``` is only for roles = 2,3,4 and ```/api/mentors/{id}```  is not even presents in wiki (but it is in Swagger)
![image](https://user-images.githubusercontent.com/62800248/121667983-7ffa5100-cab3-11eb-8ff1-e7e01117775b.png)

**Comment by serhii-devrel** [comment]
Presented the backend policy with description in the WIKI:

![1](https://user-images.githubusercontent.com/34777494/133736099-ee701481-c818-4690-9ceb-4d0d5ffc05e2.png)
![2](https://user-images.githubusercontent.com/34777494/133736105-5d36edd0-7daf-40e2-8ae6-a24be50e36f5.png)
