### ISSUE TITLE
['Registration' page] 'Publish' button is not displayed on the 'Preview' page

### ISSUE THREAD

**Issue by origami1111** [ita-social-projects/what-front#710]
**Reproducible:** always, rarely, sometimes etc.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/what-front-taqc-bug-fix

**Preconditions**
1. 'Registration' page is opened

**Steps to reproduce**
1. Fill 'First Name' field with valid data
2. Fill 'Last Name' field with valid data
3. Fill 'Email address' field with valid data
4. Fill 'Password' field with valid data (e.g.: Qwerty123)

**Actual result**
Red error message "Must contain at least one uppercase, one lowercase, one number" are showed under 'Password' field 
![Actual result(UI)](https://user-images.githubusercontent.com/71500001/126440614-fdf883b2-3f33-4eb6-aa99-6f9185968998.png)

**Expected result**
Red error message "Password must contain at least one uppercase, one lowercase, one number and one special symbol" should be shown under 'Password' field

**Labels to be added**
"Bug", Type ("UI, "Functional").

**Comment by danylo-basarab** [comment]
The issue can be closed

**Comment by Halyna-B** [comment]
The name of this issue does not match the description. And also the problem with error message in 'Registration' page was fixed in 720 issue.

![image](https://user-images.githubusercontent.com/79538541/133102034-73ee7314-c82a-48a0-90f6-963a9ccf4eac.png)
