### ISSUE TITLE
['Sign in' page] 'Forgot Password?' link does not open 'Forgot Password' page

### ISSUE THREAD

**Issue by origami1111** [ita-social-projects/what-front#712]
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/what-front-taqc-bug-fix

**Preconditions**
1. 'Sign in' page is opened

**Steps to reproduce**
1. Click 'Forgot Password?' link

**Actual result**
'Sign in' page is opened

**Expected result**
'Forgot Password' page is opened

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: critical"), Type ("UI, "Functional").

**Comment by danylo-basarab** [comment]
The issue can be closed

**Comment by Vovan1608** [comment]
https://user-images.githubusercontent.com/57871837/133109517-4ec1a953-227a-41bb-b61f-85a2eacfa1c0.mp4

**Comment by Vovan1608** [comment]
'Forgot Password?' link opens 'Forgot Password' page
