### ISSUE TITLE
['Edit student details' page] Error editing email address field

### ISSUE THREAD

**Issue by ArsenVlasov** [ita-social-projects/what-front#713]
**Environment:** Windows 10 (x64), Google Chrome v.91.0.4472.164
**Reproducible:** always

**Preconditions**

1. WHAT application is opened.
2. User with 'Admin/Secretary/Mentor' role is registered in the system.
3. User with 'Admin/Secretary/Mentor' role is logged in.
4. Select 'Student page' page.
5. Click on any student's edit icon

**Steps to reproduce**
Fill email field with "       aaa@gmail.com     " value

**Actual result**
Error message "Invalid email address" isn't displayed

**Expected result**
1. Error message "Invalid email address" is displayed

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major"), Type ("UI, "Functional")
![chrome_tu1074icro](https://user-images.githubusercontent.com/65674878/126645501-d7b20155-1658-4c56-a7df-e17a6d2d8220.png)

**Comment by serhii-devrel** [comment]
The email field was trimmed when changes saved

![1](https://user-images.githubusercontent.com/34777494/133728674-198a2f58-5764-42dc-ac2c-2f51a6b5a62a.png)
![2](https://user-images.githubusercontent.com/34777494/133728680-0ca67643-afa0-4a32-9132-585941ab614f.png)
