### ISSUE TITLE
['Forgot your password?' page | 'Sign up to WHAT' page] Email validation works incorrectly

### ISSUE THREAD

**Issue by danylo-basarab** [ita-social-projects/what-front#721]
**Environment:** 
http://localhost:8080/forgot-password
http://localhost:8080/registration
Windows 10 Pro
Google Chrome 91.0.4472.164
**Reproducible:** always

**Pre-conditions:**
WHAT project launched locally using npm.
The project opened in the browser (http://localhost:8080/forgot-password)

**Steps to reproduce:**
Enter email that starts with special symbol to 'Email adress' field.
Clear 'Email address' field and enter email that has only 1 character in top level domain.
Clear 'Email address' field and enter email that has two special symbols in a row

**Actual result:**
Values are accepted and displayed in 'Email adress' field

**Expected result:** 
The red message 'Invalid email adress' is displayed under the field.

**Links:**
[TC-47](https://jira.softserve.academy/browse/DPWHAT-47)

**Labels to be added**
"Bug", Priority ("medium"), Severity ("minor"), Type ("Functional")

**Comment by serhii-devrel** [comment]
The email field is validated by "Yup"

![3](https://user-images.githubusercontent.com/34777494/133729787-14916fcb-0e86-4bb4-bf12-9ddb04cb0f51.png)
