### ISSUE TITLE
[DOCS EDIT] Add info about pagination

### ISSUE THREAD

**Issue by so2niko** [ita-social-projects/what-front#748]
pagination duplicates also at the bottom part of screen.
Add this info to SRS
https://github.com/ita-social-projects/what-front/wiki/SRS-List-of-Courses-NEW

**Comment by TatianaMaslova** [comment]
![pagination](https://user-images.githubusercontent.com/83293693/134937520-dc7bd159-047c-48d9-bd28-dc5760264755.png)

**Comment by Halyna-B** [comment]
Updated info about pagination in the Wiki -  SRS-List-of-Courses-NEW
