### ISSUE TITLE
[documentation] - update lessons component documentation

### ISSUE THREAD

**Issue by Vovan1608** [ita-social-projects/what-front#815]

**Comment by RomanVishnevetskyi** [comment]
**### SRS List of Lessons New. documentation was update.**

![1](https://user-images.githubusercontent.com/58218838/140614703-a0117a44-712a-40f1-8432-bf04eac20a02.jpg)
![2](https://user-images.githubusercontent.com/58218838/140614728-75dfbae1-47d7-4259-b002-30f381ec445e.jpg)
